### ISSUE TITLE
Getting an Error in lib/BackendAndDatabaseManager/global_controller/encrytion_maker.dart

### ISSUE THREAD

**Issue by AnoopMasterCoder** [SamarpanCoder2002/Generation#11]
[ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: FormatException: Invalid length, must be multiple of four (at character 11) E/flutter (10145): SECRET_KEY

**Comment by SamarpanCoder2002** [comment]
Replace SECRET_KEY with a newly generated secret key using [encrypt](https://pub.dev/packages/encrypt) package.. Never disclose that SECRET_KEY in open-source.

**Comment by SamarpanCoder2002** [comment]
> [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: FormatException: Invalid length, must be multiple of four (at character 11) E/flutter (10145): SECRET_KEY

look at [encrypt](https://pub.dev/packages/encrypt) package

**Comment by AnoopMasterCoder** [comment]
Thank you it solved the Problem
