### ISSUE TITLE
There is no notification_configuration.dart file. - `'SERVER-KEY(Generated from Firebase Project Settings Cloud Messaging)'` under [notification_configuration.dart](https://github.com/SamarpanCoder2002/Generation/blob/main/lib/BackendAndDatabaseManager/general_services/notification_configuration.dart) file will replace by `SERVER-KEY` Generated Manually From Firebase Project Settings -> Cloud Messaging -> Generate New Server Key and use it as `SERVER-KEY`.</br>

### ISSUE THREAD

**Issue by johnsondarko3** [SamarpanCoder2002/Generation#58]
## 🐛 Bug Report

(A clear and concise description of what the bug is.)

### Have you read the [Contributing Guidelines](https://github.com/SamarpanCoder2002/Generation/blob/main/CONTRIBUTING.md) ?

(Write your answer here.)

**Comment by SamarpanCoder2002** [comment]
Sorry for that old update... Recently We launched Generation 2.0 . 
So some updation is not yet done.
We will try to update the documentation soon.

**Comment by SamarpanCoder2002** [comment]
> ## 🐛 Bug Report
> (A clear and concise description of what the bug is.)
> 
> ### Have you read the [Contributing Guidelines](https://github.com/SamarpanCoder2002/Generation/blob/main/CONTRIBUTING.md) ?
> (Write your answer here.)

Proper Documentation Updated @johnsondarko3

**Comment by SamarpanCoder2002** [comment]
As the problem solve, I close that issue
