### ISSUE TITLE
There is no notification_configuration.dart file

### ISSUE THREAD

**Issue by johnsondarko3** [SamarpanCoder2002/Generation#59]
## 📚 Documentation

(A clear and concise description of what the issue is.)

### Have you read the [Contributing Guidelines](https://github.com/SamarpanCoder2002/Generation/blob/main/CONTRIBUTING.md) ?

(Write your answer here.)

**Comment by SamarpanCoder2002** [comment]
We will update the documentation by EOD. Thanks for find out that issue.

**Comment by johnsondarko3** [comment]
okay

**Comment by SamarpanCoder2002** [comment]
Proper Documentation Updated @johnsondarko3
